version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: API/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge
